# Generated by Django 3.2.10 on 2022-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
