# Generated by Django 3.2.10 on 2022-02-13 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_for_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_post',
            name='AN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='for_post',
            name='file',
            field=models.FileField(default=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='For_Polls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
