# Generated by Django 3.2.10 on 2022-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20220213_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_post',
            name='file',
            field=models.FileField(blank=True, upload_to='user/files/'),
        ),
    ]
