# Generated by Django 3.2.10 on 2022-03-30 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_for_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_post',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
